### ISSUE TITLE
Tabs title bar text

### ISSUE THREAD

**Issue by f-x1-1** [sagars007/Firefox-vertical-tabs-customUI#1]
Is there a way to hide/remove or move the tabs title bar text?

**Comment by sagars007** [comment]
Can u send a pic of it? Not sure what it is exactly

**Comment by f-x1-1** [comment]
> Can u send a pic of it? Not sure what it is exactly

![8CA4D915-2C8D-4AA1-A608-5832F63F60F4](https://user-images.githubusercontent.com/77340515/131249110-f85cf729-4721-4613-b0b2-d5e39435a6f8.jpeg)

**Comment by sagars007** [comment]
> 
> 
> > Can u send a pic of it? Not sure what it is exactly
> 
> ![8CA4D915-2C8D-4AA1-A608-5832F63F60F4](https://user-images.githubusercontent.com/77340515/131249110-f85cf729-4721-4613-b0b2-d5e39435a6f8.jpeg)

Yeah it's possible to remove it. I'll send the fix soon, once I'm free.

**Comment by f-x1-1** [comment]
> 
> 
> > > Can u send a pic of it? Not sure what it is exactly
> > 
> > 
> > ![8CA4D915-2C8D-4AA1-A608-5832F63F60F4](https://user-images.githubusercontent.com/77340515/131249110-f85cf729-4721-4613-b0b2-d5e39435a6f8.jpeg)
> 
> Yeah it's possible to remove it. I'll send the fix soon, once I'm free.

Thanks, looking forward to it. :)

**Comment by sagars007** [comment]
> 
> 
> > > > Can u send a pic of it? Not sure what it is exactly
> > > 
> > > 
> > > ![8CA4D915-2C8D-4AA1-A608-5832F63F60F4](https://user-images.githubusercontent.com/77340515/131249110-f85cf729-4721-4613-b0b2-d5e39435a6f8.jpeg)
> > 
> > 
> > Yeah it's possible to remove it. I'll send the fix soon, once I'm free.
> 
> Thanks, looking forward to it. :)

I've set it in a way that when compact mode is enabled, the title bar text in nav bar is not visible (due to lack of space). So you can enable compact mode. It also doesn't show up in fullscreen and restore down states, as commented in the code. 
So the title text in nav bar only shows up in normal and touch modes, in maximized window state.

If you wanna remove it completely, remove/comment the codes from line 172 to 202 (shown below) in userChrome.css

```
@-moz-document url(chrome://browser/content/browser.xhtml){
  :root[sizemode="maximized"] > head{
    display: block;
    position: fixed;
    right: 220px;	/*center text w.r.t nav bar*/
    width: calc(100vw - 440px);  /*Window width - window control width - menuitem (English) width*/
    text-align: center;
    font-size: 11.5px;
    z-index: 1;
    pointer-events: none;
  }
    
  head > *{ display: none }
  head > title{
    display: -moz-inline-box;
    padding-top: 1px;
    max-width: 50vw;
    overflow-x: -moz-hidden-unscrollable;
    text-overflow: ellipsis;
    color: #04d9ff;
  }
  @media (-moz-os-version:windows-win10){
    :root[sizemode="maximized"] > head > title { padding-top: 6.32px}
    //:root:not([sizemode="maximized"]) > head > title { padding-top: 0px}	
 
  }
/*disabling thin nav-title-bar (title bar text in nav bar) in compact mode and when system title bar is enabled*/  
   :root[tabsintitlebar="true"] > head > title { display: -moz-inline-box !important; }      
   :root:not([tabsintitlebar="true"]) > head > title { display: none !important; }
   :root[uidensity="compact"] > head > title { display: none !important;}
} 
```
